/**
 * Created by lejoss on 8/19/16.
 */

// Restaurant ActionTypes


export const RESTAURANTS_FETCH_START = 'RESTAURANTS_FETCH_START'
export const RESTAURANTS_FETCH_SUCCESS = 'RESTAURANTS_FETCH_SUCCESS'
export const RESTAURANTS_FETCH_ERROR = 'RESTAURANTS_FETCH_ERROR'

// Order ActionTypes

export const ORDERS_FETCH_START = 'ORDERS_FETCH_START'
export const ORDERS_FETCH_SUCCESS = 'ORDERS_FETCH_SUCCESS'
export const ORDERS_FETCH_ERROR = 'ORDERS_FETCH_ERROR'

// Routes ActionTypes

export const REACT_NATIVE_ROUTER_FLUX_FOCUS = 'REACT_NATIVE_ROUTER_FLUX_FOCUS'